version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
  logstash:
    image: docker.elastic.co/logstash/logstash:5.6.2
    ports:
      - "12345:12345"
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.2
    ports:
      - "5601:5601"

